-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS condominio;
USE condominio;

CREATE TABLE IF NOT EXISTS user(
id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
cpf VARCHAR(14),
nome VARCHAR(2000),
email VARCHAR(2000),
telefone VARCHAR(2000),
empresa VARCHAR(2000),
login VARCHAR(200),
senha VARCHAR(44)
);

CREATE TABLE IF NOT EXISTS company(
id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
cnpj VARCHAR(40),
razaoSocial VARCHAR(2000),
horarioEmpresa VARCHAR(200),
temperaturaAr DECIMAL(4,2),
horarioAr VARCHAR(200)
);

select * from user;